### ISSUE TITLE
Installation methods

### ISSUE THREAD

**Issue by effigies** [jmumford/bids_sm_model_spec_gui#7]
@jmumford I was able to get going on this with:

### [uv](https://docs.astral.sh/uv/)

```
git clone https://github.com/jmumford/bids_sm_model_spec_gui
cd bds_sm_model_spec_gui
uv sync
uv run src/main_gui.py
```

I don't know how readily available Tcl/tk is on Macs, but if it's installed, that should work. `uv` will install Python 3.12 if it's not already available and link to it in the local `.venv` environment it creates.

### Conda

Tcl/tk is definitely available on conda-forge: https://anaconda.org/conda-forge/tk
If you want to make life easy for your users, you can provide an environment definition file (I call it `env.yml`, but the name isn't important):

```yaml
name: smgui
channels:
  - conda-forge
dependencies:
  # Make sure you have Python and tk available in the same environment
  - python=3.12
  - tk=8.6
  - pip
  - pip:
    - .  # Install the current package
```

Then you would just use: `conda env create -f env.yml`

Note that the `tk` in your `pyproject.toml` actually points to a random dead package on PyPI: https://pypi.org/project/tk/. You should probably remove that.
